import { Plan, AIModel } from './types';

export const APP_VERSION = "2.0.0-FINAL";
export const DEVELOPER_NAME = "Divit Bansal";

export const FIREBASE_CONFIG = {
  apiKey: "YOUR_API_KEY_HERE",
  authDomain: "nexus-ai.firebaseapp.com",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "nexus-ai.appspot.com",
  messagingSenderId: "00000000000",
  appId: "1:00000000000:web:00000000000000"
};

export const AI_MODELS: AIModel[] = [
  {
    id: 'nexus-0',
    name: 'Nexus 0',
    description: 'Standard efficient model',
    geminiModel: 'gemini-3-flash-preview',
    tier: 'Free',
    creditCost: 0, 
    builderPrice: 2,
    supportsVision: false,
    supportsAudio: false
  },
  {
    id: 'nexus-0-auto',
    name: 'Nexus 0 Auto',
    description: 'Optimized for quick tasks',
    geminiModel: 'gemini-3-flash-preview',
    tier: 'Free',
    creditCost: 1, 
    builderPrice: 3,
    supportsVision: true,
    supportsAudio: false
  },
  {
    id: 'nexus-0-plus',
    name: 'Nexus 0 Plus',
    description: 'Enhanced capabilities',
    geminiModel: 'gemini-3-flash-preview',
    tier: 'Plus',
    creditCost: 2, 
    builderPrice: 5,
    supportsVision: true,
    supportsAudio: true
  },
  {
    id: 'nexus-0-thinking',
    name: 'Nexus 0 Thinking',
    description: 'Deep reasoning engine',
    geminiModel: 'gemini-3-pro-preview',
    tier: 'Plus',
    isThinking: true,
    creditCost: 3, 
    builderPrice: 7,
    supportsVision: false,
    supportsAudio: false
  },
  {
    id: 'nexus-0-instant',
    name: 'Nexus 0 Instant',
    description: 'Low latency responses',
    geminiModel: 'gemini-3-flash-preview',
    tier: 'Plus',
    creditCost: 3, 
    builderPrice: 8,
    supportsVision: true,
    supportsAudio: true
  },
  {
    id: 'nexus-0-1',
    name: 'Nexus 0.1',
    description: 'Previous Flagship (Warmer)',
    geminiModel: 'gemini-3-pro-preview',
    tier: 'Plus',
    isNew: false,
    creditCost: 5, 
    builderPrice: 10,
    supportsVision: true,
    supportsAudio: true
  },
  {
    id: 'nexus-0-pro',
    name: 'Nexus 0 Pro',
    description: 'High accuracy model',
    geminiModel: 'gemini-3-pro-preview',
    tier: 'Pro',
    creditCost: 6, 
    builderPrice: 12,
    supportsVision: true,
    supportsAudio: true
  },
  {
    id: 'nexus-0-2',
    name: 'Nexus 0.2',
    description: 'Flagship (Thinking + Instant + Vision)',
    geminiModel: 'gemini-3-pro-preview',
    tier: 'Pro Premium',
    isNew: true,
    isThinking: true,
    creditCost: 20, 
    builderPrice: 19,
    supportsVision: true,
    supportsAudio: true
  }
];

const PLUS_MODELS = ['nexus-0', 'nexus-0-auto', 'nexus-0-plus', 'nexus-0-thinking', 'nexus-0-instant', 'nexus-0-1'];
const PRO_MODELS = [...PLUS_MODELS, 'nexus-0-pro'];
const PREMIUM_MODELS = [...PRO_MODELS, 'nexus-0-2'];

export const SUBSCRIPTION_PLANS: Plan[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    currency: '$',
    period: '/mo',
    description: 'Essential AI access.',
    features: [
      'Unlimited Nexus 0.1 Access', 
      'Nexus 0.2 (40 msgs/3h Limit)', 
      'Max 3 Images (Lifetime)',
      'No Voice Input Capability',
      'Standard Response Speed',
      'Community Forum Support',
      '2k Token Context Window',
      'No Coding Capabilities',
      'Public Cloud Infrastructure',
      'Standard Security Protocols',
      '72h Response Time'
    ],
    buttonText: 'Get Started',
    color: 'slate',
    allowedModels: ['nexus-0-1', 'nexus-0-2'],
    codingCapability: 'none',
    maxTokensOutput: 2048,
    isGodModeEligible: false,
    isVaultEligible: false,
    imageLimit: 3,
    voiceCapability: 'none',
    canExport: false
  },
  {
    id: 'go',
    name: 'Go',
    price: 5,
    currency: '$',
    period: '/mo',
    description: 'For students and casual users.',
    features: [
      'Access to Nexus 0.2', 
      'Max 10 Images (Monthly)', 
      'Basic Voice (Std. Accuracy)',
      'Mobile Optimized Interface',
      'Ad-Free Experience',
      '2 Active Parallel Chats',
      '4k Token Context Window',
      'Standard Support',
      'Reduced Queue Wait Times',
      'Basic Chat History'
    ],
    highlightFeature: 'Basic Voice',
    buttonText: 'Go Mobile',
    color: 'sky',
    allowedModels: ['nexus-0-1', 'nexus-0-2'],
    codingCapability: 'none',
    trialDuration: '1 Day',
    trialDurationMs: 24 * 60 * 60 * 1000,
    maxTokensOutput: 4096,
    isGodModeEligible: false,
    isVaultEligible: false,
    imageLimit: 10,
    voiceCapability: 'basic',
    canExport: false
  },
  {
    id: 'plus',
    name: 'Plus',
    price: 10,
    currency: '$',
    period: '/mo',
    description: 'More power for daily tasks.',
    features: [
      'Unlimited Nexus 0.2 Access', 
      'Unlimited Image Analysis',
      'Partial Coding (Snippets)', 
      'Chat Export (JSON/TXT)',
      '8k Token Context Window',
      'Priority Request Queue',
      'Basic Image Generation',
      'Email Support',
      'Search Grounding',
      'Multi-Language Support'
    ],
    highlightFeature: 'Unlimited Vision',
    buttonText: 'Upgrade to Plus',
    color: 'teal',
    allowedModels: [...PLUS_MODELS, 'nexus-0-2'],
    codingCapability: 'partial',
    trialDuration: '18 Hours',
    trialDurationMs: 18 * 60 * 60 * 1000,
    maxTokensOutput: 8192,
    isGodModeEligible: false,
    isVaultEligible: false,
    imageLimit: 'unlimited',
    voiceCapability: 'basic',
    canExport: true
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 20,
    currency: '$',
    period: '/mo',
    description: 'Professional tools.',
    features: [
      'All Plus Models Included', 
      'Neural Voice (High Accuracy)', 
      'Tone Selection (Creative/Precise)',
      'Half Coding (Functions)',
      '16k Token Context Window',
      'Voice Mode (Bi-directional)',
      'High Accuracy Logic Model',
      '3 Active Parallel Chats',
      'Complex Reasoning Engine',
      'API Access (Read-Only)'
    ],
    highlightFeature: 'Neural Voice',
    buttonText: 'Go Pro',
    color: 'blue',
    allowedModels: PRO_MODELS,
    codingCapability: 'half',
    trialDuration: '12 Hours',
    trialDurationMs: 12 * 60 * 60 * 1000,
    maxTokensOutput: 16384,
    isGodModeEligible: false,
    isVaultEligible: false,
    imageLimit: 'unlimited',
    voiceCapability: 'neural',
    canExport: true
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 30,
    currency: '$',
    period: '/mo',
    description: 'Serious power.',
    features: [
      'High Priority Nexus 0.2', 
      'Auto-Suggestions Engine',
      'Half Coding Capabilities',
      'Priority Email Support',
      '32k Token Context Window',
      'Document Analysis (Simulated)',
      'No Usage Limits',
      'Early Feature Access',
      'Advanced Data Analysis',
      'Secure Data Transmission'
    ],
    highlightFeature: 'Auto-Suggest',
    buttonText: 'Get Premium',
    color: 'indigo',
    allowedModels: PREMIUM_MODELS,
    codingCapability: 'half',
    trialDuration: '6 Hours',
    trialDurationMs: 6 * 60 * 60 * 1000,
    maxTokensOutput: 32768,
    isGodModeEligible: false,
    isVaultEligible: false,
    imageLimit: 'unlimited',
    voiceCapability: 'neural',
    canExport: true
  },
  {
    id: 'pro-premium',
    name: 'Pro Premium',
    price: 50,
    currency: '$',
    period: '/mo',
    description: 'Best of both worlds.',
    features: [
      'Unlimited Nexus 0.2 Flagship', 
      'Nexus Memory (Long-term)', 
      'Nexus Vault (Privacy Core)',
      'Team Dashboard (2 Seats)',
      '65k Token Context Window',
      'Zero Data Log Guarantee',
      'Full Knowledge Base',
      'Advanced Voice Mode',
      'Collaborative Workspaces',
      'Audit Logs'
    ],
    highlightFeature: 'Nexus Memory',
    buttonText: 'Join Pro Premium',
    color: 'violet',
    allowedModels: PREMIUM_MODELS,
    codingCapability: 'half',
    trialDuration: '5 Hours',
    trialDurationMs: 5 * 60 * 60 * 1000,
    maxTokensOutput: 65536,
    isGodModeEligible: false,
    isVaultEligible: true,
    imageLimit: 'unlimited',
    voiceCapability: 'neural',
    canExport: true
  },
  {
    id: 'super-premium',
    name: 'Super Premium',
    price: 75,
    currency: '$',
    period: '/mo',
    description: 'Elite performance.',
    features: [
      'Advanced Coding Suite', 
      'Priority Support (24/7)',
      'Deep Research Agent',
      'Self-Correction Engine',
      '100k Token Context Window',
      '5 Team Seats',
      'API Access Key',
      'Custom Model Fine-Tuning',
      'Dedicated Instance (Shared)',
      'Advanced Threat Protection'
    ],
    highlightFeature: 'Deep Research',
    buttonText: 'Unlock Super',
    color: 'purple',
    allowedModels: PREMIUM_MODELS,
    codingCapability: 'full',
    trialDuration: '3.5 Hours',
    trialDurationMs: 3.5 * 60 * 60 * 1000,
    maxTokensOutput: 100000,
    isGodModeEligible: false,
    isVaultEligible: true,
    imageLimit: 'unlimited',
    voiceCapability: 'neural',
    canExport: true
  },
  {
    id: 'max',
    name: 'Max',
    price: 100,
    currency: '$',
    period: '/mo',
    description: 'Maximum capabilities.',
    features: [
      'God Mode (Uncensored Logic)', 
      'Full Stack Coding Expert', 
      '1M Token Context Window',
      'Performance Monitor UI',
      'Dedicated TPU Instance',
      'Canvas Workspace',
      '10 Team Seats',
      'Priority API Routes',
      'Quantum-Ready Architecture',
      'Unlimited Revisions'
    ],
    highlightFeature: 'God Mode',
    buttonText: 'Maximize',
    color: 'fuchsia',
    allowedModels: PREMIUM_MODELS,
    codingCapability: 'full',
    trialDuration: '1.5 Hours',
    trialDurationMs: 1.5 * 60 * 60 * 1000,
    maxTokensOutput: 1000000,
    isGodModeEligible: true,
    isVaultEligible: true,
    imageLimit: 'unlimited',
    voiceCapability: 'neural',
    canExport: true
  },
  {
    id: 'super-max',
    name: 'Super Max',
    price: 200,
    currency: '$',
    period: '/mo',
    description: 'Beyond boundaries.',
    features: [
      'Real-time Video Analysis', 
      'Instant Generation Speed',
      'Dedicated Account Manager',
      '2M Token Context Window',
      'Neural Uplink API',
      'White-label Option',
      'Unlimited Seats',
      'SLA 99.999% Guarantee',
      'Custom Security Protocols',
      'Multi-Region Deployment'
    ],
    highlightFeature: 'Instant Speed',
    buttonText: 'Go Super Max',
    color: 'pink',
    allowedModels: PREMIUM_MODELS,
    codingCapability: 'full',
    trialDuration: '30 Minutes',
    trialDurationMs: 30 * 60 * 1000,
    maxTokensOutput: 2000000,
    isGodModeEligible: true,
    isVaultEligible: true,
    imageLimit: 'unlimited',
    voiceCapability: 'neural',
    canExport: true
  },
  {
    id: 'full-max-premium',
    name: 'Full Max Premium',
    price: 500,
    currency: '$',
    period: '/mo',
    description: 'God-mode enabled.',
    features: [
      'Absolute Access (All Models)', 
      'Infinite Context Window', 
      'Dedicated Quantum Cluster', 
      'Source Code Export',
      'Legal Liability Coverage',
      'On-Premise Deployment',
      'Custom Silicon Access',
      'The Singularity Access',
      'Neural Interface (Beta)',
      'Lifetime Updates',
      'Developer Access'
    ],
    highlightFeature: 'Quantum Cluster',
    buttonText: 'Ascend',
    color: 'rose',
    allowedModels: PREMIUM_MODELS,
    codingCapability: 'full',
    trialDuration: '7 Minutes',
    trialDurationMs: 7 * 60 * 1000,
    maxTokensOutput: 9999999,
    isGodModeEligible: true,
    isVaultEligible: true,
    imageLimit: 'unlimited',
    voiceCapability: 'neural',
    canExport: true
  }
];